# Generated by Django 5.2.4 on 2025-07-08 10:02

import django_mongodb_backend.fields
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('interactions', django_mongodb_backend.fields.EmbeddedModelArrayField(default=list, embedded_model=posts.models.Interaction)),
                ('subComments', django_mongodb_backend.fields.EmbeddedModelArrayField(default=list, embedded_model=posts.models.SubComment)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('like', 'Like'), ('share', 'Share')], max_length=10)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('images', django_mongodb_backend.fields.ArrayField(base_field=models.CharField(max_length=255), default=list)),
                ('access', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='public', max_length=10)),
                ('interactions', django_mongodb_backend.fields.EmbeddedModelArrayField(default=list, embedded_model=posts.models.Interaction)),
                ('comments', django_mongodb_backend.fields.EmbeddedModelArrayField(default=list, embedded_model=posts.models.Comment)),
                ('saved', models.BooleanField(default=False)),
                ('pinned', models.BooleanField(default=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='SubComment',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
